### ISSUE TITLE
Run Eturnal as root in docker

### ISSUE THREAD

**Issue by FarisZR** [processone/eturnal#56]
currently there doesn't seem to be a clear way to run eturnal as root, the docker `user` directive has no effect on which user runs Eturnal.

This is needed, as it isn't always possible to control who owns files needed by eturnal such as SSL certs.

there is a workaround here:
https://github.com/processone/eturnal/issues/55#issuecomment-1742183379

**Comment by sando38** [comment]
Can you test with the recent commit, if that works for your setup?

```shell
sudo docker run --rm --user 0 --name eturnal -e ETURNAL_USER=root -d ghcr.io/processone/eturnal:edge
```

**Comment by FarisZR** [comment]
```bash
test-eturnal-1  | su: unknown user root
```

using this test compose file:
```yaml
services:
  eturnal:
    image: ghcr.io/processone/eturnal:edge
    user: 0:0 # to access caddy certs
    # ports:
      # - '3478:3478'
      # - '49000-49200:49000-49200'
      # - '3478:3478/udp'
      # - '49000-49200:49000-49200/udp'
    environment:
      - ETURNAL_USER=root
    volumes:
      - caddy_data:/caddy-data:ro
    configs:
        - source: eturnal
          target: /etc/eturnal.yml

configs:
  eturnal:
    file: ./eturnal.yml

volumes:
  caddy_data:
    external: true
```

**Comment by sando38** [comment]
This works for me:

```shell
saarko@raspberrypi:~ $ sudo docker compose up -d
[+] Running 2/2
 ✔ Network saarko_default      Created                                                                                                                                          0.1s 
 ✔ Container saarko-eturnal-1  Started                                                                                                                                          1.0s 
saarko@raspberrypi:~ $ sudo docker logs saarko-eturnal-1  
Cannot query stun.conversations.im:3478: can't assign requested address
Exec: /opt/eturnal/erts-14.0.2/bin/erlexec -noinput +Bd -boot /opt/eturnal/releases/1.12.0+17/start -mode embedded -boot_var SYSTEM_LIB_DIR /opt/eturnal/lib -config /opt/eturnal/releases/1.12.0+17/sys.config -args_file /opt/eturnal/releases/1.12.0+17/vm.args -erl_epmd_port 3470 -start_epmd false -- foreground
Root: /opt/eturnal
/opt/eturnal
2023-10-01 20:41:03.959067+00:00 [notice] Starting eturnal 1.12.0+17 on Erlang/OTP 26 (ERTS 14.0.2)
2023-10-01 20:41:03.959294+00:00 [info] Got no NOTIFY_SOCKET, notifications disabled
2023-10-01 20:41:03.959412+00:00 [info] Relay IPv4 address: xxx.xxx.xxx.xxx (port range: 49152-65535)
2023-10-01 20:41:03.959478+00:00 [info] Relay IPv6 address not configured
2023-10-01 20:41:03.959568+00:00 [info] Listening on 127.0.0.1:3470 (tcp) (Erlang protocol version 5)
2023-10-01 20:41:03.959877+00:00 [info] Started mod_log_stun
2023-10-01 20:41:03.961166+00:00 [info] Listening on [::]:3478 (udp) (STUN/TURN)
2023-10-01 20:41:03.962004+00:00 [info] Listening on [::]:3478 (tcp) (STUN/TURN)
saarko@raspberrypi:~ $ cat docker-compose.yml 
services:
  eturnal:
    image: ghcr.io/processone/eturnal:edge@sha256:34fe2746fd48fbf31203d0a3f9e43aefb12d639cd6ea2c4f7a7dff9af2ad68b5
    user: 0:0 # to access caddy certs
    # ports:
      # - '3478:3478'
      # - '49000-49200:49000-49200'
      # - '3478:3478/udp'
      # - '49000-49200:49000-49200/udp'
    environment:
      - ETURNAL_USER=root
```

**Comment by FarisZR** [comment]
I just tried it on X86 and it still doesn't work, not sure where the issue is.

**Comment by FarisZR** [comment]
removing `user: 0:0` fixes it, but then there is still the permission issue.

**Comment by sando38** [comment]
You have the newest `edge` image?

**Comment by FarisZR** [comment]
im using the hash you used in your example
`ghcr.io/processone/eturnal:edge@sha256:34fe2746fd48fbf31203d0a3f9e43aefb12d639cd6ea2c4f7a7dff9af2ad68b5`

**Comment by sando38** [comment]
Just to make sure, can you bring the compose down with `docker compose down` and start it up again with `docker compose up -d`?

**Comment by FarisZR** [comment]
Huh, that fixed it. even though docker explictly rebuilt the container.
i will test it if it works now.

**Comment by FarisZR** [comment]
it works now, but it doesn't seem to start to actually listen on the ports?
```bash
docker compose up
[+] Running 2/2
 ✔ Network test_default      Created                                                                     0.1s 
 ✔ Container test-eturnal-1  Created                                                                     0.4s 
Attaching to test-eturnal-1
test-eturnal-1  | Cannot query stun.conversations.im:3478: can't assign requested address
test-eturnal-1  | Exec: /opt/eturnal/erts-14.0.2/bin/erlexec -noinput +Bd -boot /opt/eturnal/releases/1.12.0+17/start -mode embedded -boot_var SYSTEM_LIB_DIR /opt/eturnal/lib -config /opt/eturnal/releases/1.12.0+17/sys.config -args_file /opt/eturnal/releases/1.12.0+17/vm.args -erl_epmd_port 3470 -start_epmd false -- foreground
test-eturnal-1  | Root: /opt/eturnal
test-eturnal-1  | /opt/eturnal
```

compose:

```yaml
services:
  eturnal:
    image: ghcr.io/processone/eturnal:edge@sha256:34fe2746fd48fbf31203d0a3f9e43aefb12d639cd6ea2c4f7a7dff9af2ad68b5
    userns_mode: host
    user: 0:0 # to access caddy certs
    ports:
      - '3478:3478'
      - '49000-49200:49000-49200'
      - '3478:3478/udp'
      - '49000-49200:49000-49200/udp'
    environment:
      - ETURNAL_USER=root
    volumes:
      - caddy_data:/caddy-data:ro
    configs:
        - source: eturnal
          target: /etc/eturnal.yml

configs:
  eturnal:
    file: ./eturnal.yml

volumes:
  caddy_data:
    external: true
```

**Comment by sando38** [comment]
What loglevel have you set?

**Comment by sando38** [comment]
You may check with:
```
$ sudo docker exec test-eturnal-1 netstat -tuna 
Active Internet connections (servers and established)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       
tcp        0      0 127.0.0.1:3470          0.0.0.0:*               LISTEN      
tcp        0      0 127.0.0.11:41645        0.0.0.0:*               LISTEN      
tcp        0      0 127.0.0.1:43338         127.0.0.1:3470          TIME_WAIT   
tcp        0      0 :::3478                 :::*                    LISTEN      
udp        0      0 127.0.0.11:36733        0.0.0.0:*                           
udp        0      0 :::3478                 :::*  
```

**Comment by FarisZR** [comment]
> What log level have you set?

i've just set it to debug, still no logs about mounting into ports
it shows up in netstat, but its from dockerd, not sure that means eturnal is actually listening.

**Comment by sando38** [comment]
Can you provide the logs you are sseeing?

**Comment by FarisZR** [comment]
```bash
docker compose up
[+] Running 2/2
 ✔ Network test_default      Created                                                                     0.3s 
 ✔ Container test-eturnal-1  Created                                                                     0.7s 
Attaching to test-eturnal-1
test-eturnal-1  | Cannot query stun.conversations.im:3478: can't assign requested address
test-eturnal-1  | Exec: /opt/eturnal/erts-14.0.2/bin/erlexec -noinput +Bd -boot /opt/eturnal/releases/1.12.0+17/start -mode embedded -boot_var SYSTEM_LIB_DIR /opt/eturnal/lib -config /opt/eturnal/releases/1.12.0+17/sys.config -args_file /opt/eturnal/releases/1.12.0+17/vm.args -erl_epmd_port 3470 -start_epmd false -- foreground
test-eturnal-1  | Root: /opt/eturnal
test-eturnal-1  | /opt/eturnal
```

compose:
```yaml
services:
  eturnal:
    image: ghcr.io/processone/eturnal:edge@sha256:34fe2746fd48fbf31203d0a3f9e43aefb12d639cd6ea2c4f7a7dff9af2ad68b5
    userns_mode: host
    user: 0:0 # to access caddy certs
    ports:
      - '3478:3478'
      - '49000-49200:49000-49200'
      - '3478:3478/udp'
      - '49000-49200:49000-49200/udp'
    environment:
      - ETURNAL_USER=root
    volumes:
      - caddy_data:/caddy-data:ro
    configs:
        - source: eturnal
          target: /etc/eturnal.yml

configs:
  eturnal:
    file: ./eturnal.yml

volumes:
  caddy_data:
    external: true
```

Eturnal.yml
```yaml
# eturnal STUN/TURN server configuration file.
#
# This file is written in YAML. The YAML format is indentation-sensitive, please
# MAKE SURE YOU INDENT CORRECTLY.
#
# See: https://eturnal.net/doc/#Global_Configuration

eturnal:

  ## Shared secret for deriving temporary TURN credentials (default: $RANDOM):
  secret: "xxxxx"

  ## The server's public IPv4 address (default: autodetected):
  relay_ipv4_addr: "89.168.104.205"
  ## The server's public IPv6 address (optional):
  relay_ipv6_addr: "2603:c020:8011:9ede::23"
  realm: turn.fariszr.com

  listen:
    -
      ip: "::"
      port: 3478
      transport: udp
    -
      ip: "::"
      port: 3478
      transport: auto #TLS AND TCP

  ## TLS certificate/key files (must be readable by 'eturnal' user!):
  tls_crt_file: /caddy-data/caddy/certificates/acme-v02.api.letsencrypt.org-directory/turn.fariszr.com/turn.fariszr.com.crt
  tls_key_file: /caddy-data/caddy/certificates/acme-v02.api.letsencrypt.org-directory/turn.fariszr.com/turn.fariszr.com.key

  ## UDP relay port range (usually, several ports per A/V call are required):
  relay_min_port: 49000     # This is the default.
  relay_max_port: 49200     # This is the default.

  ## Reject TURN relaying to the following addresses/networks:
  blacklist_peers:
    - recommended           # Expands to various addresses/networks recommended
                            # to be blocked. This is the default.

  ## If 'true', close established calls on expiry of temporary TURN credentials:
  strict_expiry: false      # This is the default.

  ## Logging configuration:
  log_level: debug           # critical | error | warning | notice | info | debug
  log_rotate_size: 10485760 # 10 MiB (default: unlimited, i.e., no rotation).
  log_rotate_count: 2      # Keep 10 rotated log files.
  #log_dir: stdout          # Enable for logging to the terminal/journal.

  ## See: https://eturnal.net/doc/#Module_Configuration
  modules:
    mod_log_stun: {}        # Log STUN queries (in addition to TURN sessions).
    #mod_stats_influx: {}   # Log STUN/TURN events into InfluxDB.
    #mod_stats_prometheus:  # Expose STUN/TURN and VM metrics to Prometheus.
    #  ip: any              # This is the default: Listen on all interfaces.
    #  port: 8081           # This is the default.
    #  tls: false           # This is the default.
    #  vm_metrics: true     # This is the default.
```
