### ISSUE TITLE
mod_stats_prometheus: make bucket sizes configurable

### ISSUE THREAD

**Issue by sando38** [processone/eturnal#61]
Currently bucket sizes for time and data are hard coded. These values are tailored for Audio/Video use cases, however, TURN is not only used for these scenarios. Therefore, provide a configurational option to define them via the module section, e.g. like this:

```yaml
mod_stats_prometheus:
  buckets_time: [10, 20, 30, 45, 60, 120, 300]
  buckets_size: [1024, 2048, 4096, 8192] 
```

https://github.com/processone/eturnal/blob/a5f7a1326c02772a47c5b7bd420e85607bc3020f/src/mod_stats_prometheus.erl#L31-L50
