### ISSUE TITLE
memory usage

### ISSUE THREAD

**Issue by docjojo** [processone/eturnal#76]
I have eturnal running on a VPS

CPU:    2 vCore
RAM:     2 GB
80 GB NVMe SSD

I have coturn running on the same machine (different ports).
Eturnal is handling more traffic, but CPU usage is significantly differnt.

Any idea how to reduce the usage?

179,7% for eturnal, 4,7% for coturn.
both report to prometheus.

config:
```
  log_level: error
  log_dir: /opt/eturnal/log

  modules:
    #mod_log_stun: {}       # Log STUN queries (in addition to TURN sessions).
    mod_stats_prometheus:  # Expose STUN/TURN and VM metrics to Prometheus.
```

```
 113344 eturnal   20   0 2791620 643776  33384 S 179.7  33.7  68:17.24 beam.smp                                                                                       
    693 turnser+  20   0  550672  69444    692 S   4.7   3.6  11:35.31 turnserver                                                                                     
     94 root      20   0       0      0      0 S   2.7   0.0  18:28.96 kswapd0    
```
