### ISSUE TITLE
"Rejecting permission creation request" when using TLS

### ISSUE THREAD

**Issue by kladderadeng** [processone/eturnal#86]
After I got everything up and running with UDP/TCP on 3478, I wanted to implement TLS. I had issues with Let's Encrypt, not being accepted by my Nextcloud and Synapse instance, but with a ZeroSSL certificate, testing with for example https://webrtc.github.io/samples/src/content/peerconnection/trickle-ice/ works and I do not get SSL errors anymore during the handshake.

To make sure SSL actually works, I disabled the 3478 listeners in the eturnal.yml and then realized, that it is not fully working yet. When making calls, they do not get established / no audio can be transmitted.

The message I get in the logs reads `Rejecting permission creation request` and I wonder if I am missing something in my eturnal.yml regarding permissions.

I run the Docker ACME version.

Eturnal Log:
```
eturnal       | 2025-03-09 11:38:54.135927+00:00 [info] Accepting long-term STUN/TURN authentication [TLS, session 45wmegloktnu, user 1741604101:@user:domain.tld, client 80.187.xxx.xxx:7002]
eturnal       | 2025-03-09 11:38:54.136184+00:00 [info] Accepting long-term STUN/TURN authentication [TLS, session 45wmegloktnu, user 1741604101:@user:domain.tld, client 80.187.xxx.xxx:7002]
eturnal       | 2025-03-09 11:38:54.136206+00:00 [notice] Rejecting permission creation request: Forbidden [TLS, session 45wmegloktnu, user 1741604101:@user:domain.tld, client 80.187.xxx.xxx:7002, relay 139.142.xxx.xxx:49216]
eturnal       | 2025-03-09 11:38:54.136740+00:00 [info] Creating TURN permission for 89.58.xxx.xxx [TLS, session 45wmegloktnu, user 1741604101:@user:domain.tld, client 80.187.xxx.xxx:7002, relay 139.142.xxx.xxx:49216]
eturnal       | 2025-03-09 11:38:54.385957+00:00 [info] Accepting long-term STUN/TURN authentication [TLS, session 45wmegloktnu, user 1741604101:@user:domain.tld, client 80.187.xxx.xxx:7002]
eturnal       | 2025-03-09 11:38:54.386328+00:00 [info] Refreshing TURN permission for 89.58.xxx.xxx [TLS, session 45wmegloktnu, user 1741604101:@user:domain.tld, client 80.187.xxx.xxx:7002, relay 139.142.xxx.xxx:49216]
eturnal       | 2025-03-09 11:38:54.386516+00:00 [info] Binding TURN channel 4001 for peer 89.58.xxx.xxx:60897 [TLS, session 45wmegloktnu, user 1741604101:@user:domain.tld, client 80.187.xxx.xxx:7002, relay 139.142.xxx.xxx:49216]
eturnal       | 2025-03-09 11:39:05.077357+00:00 [info] Accepting long-term STUN/TURN authentication [TLS, session 45wmegloktnu, user 1741604101:@user:domain.tld, client 80.187.xxx.xxx:7002]
eturnal       | 2025-03-09 11:39:05.077646+00:00 [info] Client requested closing the TURN session [TLS, session 45wmegloktnu, user 1741604101:@user:domain.tld, client 80.187.xxx.xxx:7002, relay 139.142.xxx.xxx:49216]
eturnal       | 2025-03-09 11:39:05.078018+00:00 [info] Deleting TURN allocation [TLS, session 45wmegloktnu, user 1741604101:@user:domain.tld, client 80.187.xxx.xxx:7002, relay 139.142.xxx.xxx:49216]
eturnal       | 2025-03-09 11:39:05.078160+00:00 [notice] Relayed 79 KiB (in 44221 B / 641 packets, out 36497 B / 492 packets), duration: 22 seconds [TLS, session 45wmegloktnu, user 1741604101:@user:domain.tld, client 80.187.xxx.xxx:7002, relay 139.142.xxx.xxx:49216]
```

My eturnal.yml
```yml
eturnal:
  secret: "supersecret"
  listen:
    #-
    #  ip: "::"
    #  port: 3478
    #  transport: udp
    #-
    #  ip: "::"
    #  port: 3478
    #  transport: tcp
    -
      ip: "::"
      port: 5349
      transport: tls
  tls_crt_file: /opt/eturnal/tls/fullchain.pem
  tls_key_file: /opt/eturnal/tls/key.pem
  relay_min_port: 49160     # This is the default.
  relay_max_port: 49260     # This is the default.
  blacklist_peers:
    - recommended           # Expands to various addresses/networks recommended
                            # to be blocked. This is the default.
  strict_expiry: false      # This is the default.
  log_level: info           # critical | error | warning | notice | info | debug
  log_rotate_size: 10485760 # 10 MiB (default: unlimited, i.e., no rotation).
  log_rotate_count: 10      # Keep 10 rotated log files.
  log_dir: stdout          # Enable for logging to the terminal/journal.
  modules:
    mod_log_stun: {}        # Log STUN queries (in addition to TURN sessions).
```

I only assume that this is my issue. Eturnal TURNS/STUNS and Media Relay should work fine with only TLS enabled, right?

For 5349 I opened and forwarded UDP/TCP, as I did for 3478 when testing without TLS.
