### ISSUE TITLE
Configuring TLS and credentials doesn't work on Windows

### ISSUE THREAD

**Issue by mmtune** [processone/eturnal#88]
how do you add the credentails and the tls to the eturnal.yml file
on windows eturnal doesn't start when add the tls or credentials.
File below.

```yaml
# eturnal STUN/TURN server configuration file.
#
# This file is written in YAML. The YAML format is indentation-sensitive, please
# MAKE SURE YOU INDENT CORRECTLY.
#
# See: https://eturnal.net/doc/#Global_Configuration

eturnal:


  ## Shared secret for deriving temporary TURN credentials (default: $RANDOM):
  secret: "mmtune"
  
  
  ## The server's public IPv4 address (default: autodetected):
  relay_ipv4_addr: "192.168.1.10"
  ## The server's public IPv6 address (optional):
  #relay_ipv6_addr: "2001:db8::4"

  listen:
    -
      ip: "192.168.1.10"
      port: 3478
      transport: udp
      
    -
      ip: "192.168.1.10"
      port: 3479
      transport: tcp
      
    -
      ip: "192.168.1.10"
      port: 5349
      transport: tls
      
    -  
  ## TLS certificate/key files (must be readable by 'eturnal' user!): 
  tls_crt_file: /etc/eturnal/tls/turn_server_cert.pem
  tls_key_file: /etc/eturnal/tls/turn_server_key.pem
  
   Credentials:
      mmtu: test
 
  ## UDP relay port range (usually, several ports per A/V call are required):
  relay_min_port: 49152     # This is the default.
  relay_max_port: 65535     # This is the default.

  ## Reject TURN relaying to the following addresses/networks:
  blacklist_peers:
    - recommended           # Expands to various addresses/networks recommended
                            # to be blocked. This is the default.

  ## If 'true', close established calls on expiry of temporary TURN credentials:
  strict_expiry: true      # This is the default.

  ## Logging configuration:
  log_level: info          # critical | error | warning | notice | info | debug
  log_rotate_size: 10485760 # 10 MiB (default: unlimited, i.e., no rotation).
  log_rotate_count: 10      # Keep 10 rotated log files.
  log_dir: "C:/Program Files/eturnal/log"
  run_dir: "C:/Program Files/eturnal/run"

  ## See: https://eturnal.net/doc/#Module_Configuration
  modules:
    mod_log_stun: {}        # Log STUN queries (in addition to TURN sessions).
    #mod_stats_influx: {}   # Log STUN/TURN events into InfluxDB.
    #mod_stats_prometheus:  # Expose STUN/TURN and VM metrics to Prometheus.
    #ip: any              # This is the default: Listen on all interfaces.
    #port: 8081           # This is the default.
    #tls: true           # This is the default.
    #vm_metrics: true     # This is the default.
```

**Comment by weiss** [comment]
```yaml
   Credentials:
      mmtu: test
```

The devil is in the details:

1. The `credentials` option must be written lower-case, i.e. the upper-case `C` won't work.
2. The file's [YAML syntax][1] is indentation-sensitive: There's an additional space character at the beginning of those two lines that you must remove.

[1]: https://www.yaml.info/learn/bestpractices.html

**Comment by mmtune** [comment]
eturnal doesn't work on windows. You can't add tls or credential to the yaml file. it won't start. full stop.

**Comment by mmtune** [comment]
share secret doesn't work.
$username = "1735686000"         # For credentials valid until 2025-01-01.
$secret = "secretuser" # As specified in your eturnal.yml.

$sha = [System.Security.Cryptography.KeyedHashAlgorithm]::Create("HMACSHA1")
$sha.Key = [System.Text.Encoding]::UTF8.Getbytes($secret)
$password = [Convert]::Tobase64String($sha.ComputeHash([System.Text.Encoding]::UTF8.Getbytes(${username})))

echo $username
echo $password

**Comment by weiss** [comment]
> eturnal doesn't work on windows.

We've tested eturnal on Windows successfully, so we should try to figure out how your setup is different from ours.  Do you see any entries in `C:\Program Files\eturnal\log\eturnal.log`?

> You can't add tls or credential to the yaml file. it won't start.

Does eturnal start if you use the default configuration file?

If so, could you try to make one change at a time: e.g., add only a TLS listener, check the log file, and if you see no entry at all, copy-paste the configuration file so that we can check it?

**Comment by weiss** [comment]
> share secret doesn't work.

I'd suggest testing with static credentials first, and once that works, looking into shared secret authentication.

**Comment by mmtune** [comment]
Yes, it start with default configuration. But it allows everyone to connect
to the server.

**Comment by weiss** [comment]
eturnal doesn't allow anyone to create TURN sessions by default. (Only STUN queries are accepted.)

Anyway, did you check the `C:\Program Files\eturnal\log\eturnal.log` file as I suggested above? If you see no log entries at all, eturnal is most likely still stumbling over invalid configuration syntax during startup. Unfortunately, eturnal's startup error messages are hidden by Windows, so spotting the issue without seeing your configuration is tricky.

One suggestion would be to copy-paste the following configuration, which works just fine for me on Windows, and continue from there.

```yaml
# This file is written in YAML. The YAML format is indentation-sensitive, please
# MAKE SURE YOU INDENT CORRECTLY.
#
# See: https://eturnal.net/doc/#Global_Configuration

eturnal:

  listen:
    -
      ip: "0.0.0.0"
      port: 3478
      transport: udp
    -
      ip: "::"
      port: 3478
      transport: udp
    -
      ip: "0.0.0.0"
      port: 5349
      transport: tls
    -
      ip: "::"
      port: 5349
      transport: tls

  ## TURN authentication (support both dynamic and static credentials):
  secret: "change-this!"
  credentials:
    alice: "change-this-2"

  ## The server's public IPv4 address:
  relay_ipv4_addr: "203.0.113.4"
  ## UDP relay port range, must be accessible from the outside:
  relay_min_port: 50000
  relay_max_port: 54999

  log_dir: "C:/Program Files/eturnal/log"
  run_dir: "C:/Program Files/eturnal/run"

  modules:
    mod_log_stun: {} # Log STUN queries (in addition to TURN sessions).
```

(You need to specify at least the `relay_ipv4_addr` to make TURN relaying work, though.)
